### ISSUE TITLE
layer visibility icons

### ISSUE THREAD

**Issue by larsenwork** [fontforge/dark-theme#1]
How did you get to change the layer visibility icon? 

I tried adding visiblility_on.png, visiblility_off.png to pixmaps but that didn't do the trick? Do they need to be special dimensions or turned on somewhere?

**Comment by pathumego** [comment]
@andreaslarsen yep I had to add an extra line on theme file. I can not remember exactly. Ill let you know today! And sorry about delay I was on a mini holiday :)

**Comment by pathumego** [comment]
Adding these to theme file will do the trick for visibility icons. BUT if a user changes any settings on X Resource Editor it will disappear. I will file an issue for this.

```
Gdraw.GVisibilityBoxOn.Image:visiblility_on.png
Gdraw.GVisibilityBoxOff.Image:visiblility_off.png
```

**Comment by larsenwork** [comment]
cheers, there are many issues with the x resource editor though - I make edits directly ind the theme files instead :)
